name: DaemonApp

options:
  bundleIdPrefix: com.nugget
  projectFormat: xcode15_0

targets:
  DaemonApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DaemonApp
        excludes:
          - entitlements.plist
          - daemonmanager
          - daemon.cfg
    resources:
      - path: DaemonApp/daemonmanager
      - path: DaemonApp/daemon.cfg
    info:
      path: DaemonApp/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
